### ISSUE TITLE
Convert to MIDI for external gear

### ISSUE THREAD

**Issue by voronianski** [ddj231/Handel#2]
First of all thanks sharing this project! Very inspirational :)

Afaics you're using predefined set of synths via Tone.js to generate sounds. However I thought it would be also super fun to use Handel as a replacement for MIDI for external synths (e.g. hardware and VSTs). I'm assuming it should be possible to do with Tone.js as well, right?

**Comment by ddj231** [comment]
@voronianski Thanks for the feature request!

Having the option to output with external synths would be a nice addition, but I'm currently not sure whether it would work best as an addition to the ```HandelInterpreter ``` class or if it would work best as a separate interpreter which exports to MIDI: ```HandelInterpreterToMIDI```

I think Tonejs/midi would work for this.  And ideally the ```RunHandel``` function  would take a configuration that allows the method of output of a run to be configured

**Comment by ddj231** [comment]
Hi! As of [v0.3.0](https://github.com/ddj231/Handel/releases/tag/0.3.0) commit 71d188c2, Handel now supports compiling to MIDI. This is a feature that will grow as the language grows, at the moment all chunks are individual tracks and notes are scheduled appropriately.

To compile to midi and download the midi file, you pass a config object with outputMidi set to true in the RunHandel function, like so:
```
const config = {outputMidi: true};
Handel.RunHandel(`start play E4 for 1b finish`, config);
```

Also the [Handel Web Editor](https://ddj231.github.io/Handel-Web-Editor/) now uses this functionality to allow exporting midi from there (under the file tab).

This does not fully cover your use case (as it is not a replacement for MIDI) but this seems like the best option at the moment. Closing for now, but I can reopen the issue --  open to suggestions, and PR's if the original use case is feasible.
